sudo: true
langague: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - apt-get update -qq
  - apt-get install -qq python3-dev python3-pip python3-virtualenv freetds-dev
script:
  - "make test"
